<h2 align='center' style='color:purple'>Finding best model and hyper parameter tunning using GridSearchCV</h2>

**Load iris flower dataset**

In [1]:
import pandas as pd

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [3]:
df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
df['flower']=iris.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

<h3 style='color:blue'>Approach 1: Use train_test_split and manually tune parameters by trial and error</h3>

In [5]:
x = df.drop('flower', axis=1)
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
y = df['flower']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: flower, Length: 150, dtype: int32

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [8]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
28                 5.2               3.4                1.4               0.2
107                7.3               2.9                6.3               1.8
7                  5.0               3.4                1.5               0.2
37                 4.9               3.6                1.4               0.1
23                 5.1               3.3                1.7               0.5
..                 ...               ...                ...               ...
91                 6.1               3.0                4.6               1.4
73                 6.1               2.8                4.7               1.2
52                 6.9               3.1                4.9               1.5
96                 5.7               2.9                4.2               1.3
69                 5.6               2.5                3.9               1.1

[105 rows x 4 columns]

In [9]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
45                 4.8               3.0                1.4               0.3
117                7.7               3.8                6.7               2.2
19                 5.1               3.8                1.5               0.3
60                 5.0               2.0                3.5               1.0
3                  4.6               3.1                1.5               0.2
34                 4.9               3.1                1.5               0.2
12                 4.8               3.0                1.4               0.1
46                 5.1               3.8                1.6               0.2
35                 5.0               3.2                1.2               0.2
145                6.7               3.0                5.2               2.3
140                6.7               3.1                5.6               2.4
22                 4.6               3.6                1.0               0.2
11                 4.8               3.4                1.6               0.2
94                 5.6               2.7                4.2               1.3
58                 6.6               2.9                4.6               1.3
139                6.9               3.1                5.4               2.1
148                6.2               3.4                5.4               2.3
82                 5.8               2.7                3.9               1.2
78                 6.0               2.9                4.5               1.5
88                 5.6               3.0                4.1               1.3
132                6.4               2.8                5.6               2.2
103                6.3               2.9                5.6               1.8
16                 5.4               3.9                1.3               0.4
90                 5.5               2.6                4.4               1.2
30                 4.8               3.1                1.6               0.2
66                 5.6               3.0                4.5               1.5
53                 5.5               2.3                4.0               1.3
121                5.6               2.8                4.9               2.0
5                  5.4               3.9                1.7               0.4
56                 6.3               3.3                4.7               1.6
134                6.1               2.6                5.6               1.4
44                 5.1               3.8                1.9               0.4
125                7.2               3.2                6.0               1.8
61                 5.9               3.0                4.2               1.5
41                 4.5               2.3                1.3               0.3
111                6.4               2.7                5.3               1.9
4                  5.0               3.6                1.4               0.2
87                 6.3               2.3                4.4               1.3
128                6.4               2.8                5.6               2.1
118                7.7               2.6                6.9               2.3
102                7.1               3.0                5.9               2.1
99                 5.7               2.8                4.1               1.3
50                 7.0               3.2                4.7               1.4
62                 6.0               2.2                4.0               1.0
18                 5.7               3.8                1.7               0.3

In [10]:
from sklearn.svm import SVC

In [16]:
model = SVC(kernel='rbf', C=1, gamma='auto')

model.fit(X_train,y_train)

model.score(X_test, y_test)

1.0

<h3 style='color:blue'>Approach 2: Use K Fold Cross validation</h3>

**Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation**

In [17]:
from sklearn.model_selection import cross_val_score

In [20]:
sv1=cross_val_score(SVC(kernel='rbf',C=1,gamma='auto'),x, y, cv=5)
sv1

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
sv1.mean()

0.9800000000000001

In [22]:
sv2=cross_val_score(SVC(kernel='poly',C=1,gamma='auto'),x, y, cv=5)
sv2

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [23]:
sv2.mean()

0.9666666666666666

In [24]:
sv3=cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),x, y, cv=5)
sv3

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [25]:
sv3.mean()

0.9666666666666668

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
sv3 = cross_val_score(DecisionTreeClassifier(), x, y, cv=5)
sv3

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [28]:
sv3.mean()

0.9666666666666668

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
sv3 = cross_val_score(GaussianNB(), x, y, cv=5)
sv3

array([0.93333333, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [31]:
sv3.mean()

0.9533333333333334

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
sv4 = cross_val_score(KNeighborsClassifier(n_neighbors=3), x, y, cv=5)
sv4

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [34]:
sv4.mean()

0.9666666666666668

<h3 style='color:blue'>Use GridSearchCV</h3>

**GridSearchCV does exactly same thing as for loop above but in a single line of code**

In [11]:
from sklearn.model_selection import GridSearchCV

In [12]:

clf = GridSearchCV(SVC(gamma='auto'), {
    'C': [1,10,20,30],
    'kernel': ['rbf','linear', 'poly']
}, cv=5)

clf.fit(x, y)

clf.cv_results_

{'mean_fit_time': array([0.00720916, 0.00551276, 0.00712705, 0.00520501, 0.00520978,
        0.01222043, 0.00583301, 0.00483398, 0.0188796 , 0.00703735,
        0.00595355, 0.01997676]),
 'std_fit_time': array([0.0045655 , 0.00044935, 0.00247393, 0.00038435, 0.00101686,
        0.00547219, 0.00074445, 0.00039781, 0.01173802, 0.00176796,
        0.00102234, 0.01226158]),
 'mean_score_time': array([0.0041048 , 0.00361848, 0.00457177, 0.00423388, 0.00445218,
        0.00431833, 0.00491328, 0.00409942, 0.00464149, 0.0047359 ,
        0.00450993, 0.00342531]),
 'std_score_time': array([0.00112522, 0.00048399, 0.00090357, 0.00060032, 0.00193254,
        0.00133699, 0.00192457, 0.00065977, 0.0008267 , 0.00122275,
        0.00063504, 0.00051223]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly', 'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'poly'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667, 1.        , 0.96666667, 0.96666667,
        1.        , 0.96666667]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.93333333,
        0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.98      , 0.97333333,
        0.96666667, 0.96666667, 0.96666667, 0.95333333, 0.96      ,
        0.96      , 0.95333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.0421637 , 0.01632993, 0.03887301,
        0.0421637 , 0.03651484, 0.0421637 , 0.03399346, 0.03887301,
        0.04898979, 0.03399346]),
 'rank_test_score': array([ 1,  1,  6,  1,  4,  6,  5,  6, 11,  9,  9, 11])}

In [13]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007209,0.004565,0.004105,0.001125,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005513,0.000449,0.003618,0.000484,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.007127,0.002474,0.004572,0.000904,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.005205,0.000384,0.004234,0.000600,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.005210,0.001017,0.004452,0.001933,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
5,0.012220,0.005472,0.004318,0.001337,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.005833,0.000744,0.004913,0.001925,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
7,0.004834,0.000398,0.004099,0.000660,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
8,0.018880,0.011738,0.004641,0.000827,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
9,0.007037,0.001768,0.004736,0.001223,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
10,0.005954,0.001022,0.004510,0.000635,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
11,0.019977,0.012262,0.003425,0.000512,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11

In [ ]:
df[['param_C','param_kernel','mean_test_score']]

In [14]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [15]:
clf.best_score_

0.9800000000000001

In [35]:
df = pd.read_csv("Breast_Cancer_Diagnostic.csv")

In [36]:
df

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,M
...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,M
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,M
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,M
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,M
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,B

In [37]:
x = df.drop('diagnosis', axis = 1)
y = df['diagnosis']

In [38]:

clf = GridSearchCV(SVC(gamma='auto'), {
    'C': [1,10,20,30],
    'kernel': ['rbf','linear']
}, cv=5)

clf.fit(x, y)

clf.cv_results_

{'mean_fit_time': array([0.04356503, 1.45987306, 0.04814639, 8.5045639 , 0.04914646,
        5.50939631, 0.05048671, 6.19449162]),
 'std_fit_time': array([1.18712575e-03, 6.57244892e-01, 6.99447578e-03, 2.93672741e+00,
        4.75976351e-03, 1.50799513e+00, 2.49350712e-03, 1.64853665e+00]),
 'mean_score_time': array([0.02193556, 0.0064291 , 0.02104545, 0.00484056, 0.02122655,
        0.00496454, 0.024266  , 0.0055222 ]),
 'std_score_time': array([0.00157432, 0.00092498, 0.00080783, 0.00052132, 0.00096066,
        0.00034013, 0.00200385, 0.00058264]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.71052632, 0.85964912, 0.70175439, 0.88596491, 0.70175439,
        0.90350877, 0.70175439, 0.88596491]),
 'split1_test_score': array([0.71929825, 0.88596491, 0.71929825, 0.89473684, 0.71929825,
        0.90350877, 0.71929825, 0.92982456]),
 'split2_test_score': array([0.74561404, 0.92982456, 0.75438596, 0.93859649, 0.75438596,
        0.92982456, 0.75438596, 0.93859649]),
 'split3_test_score': array([0.72807018, 0.92982456, 0.71052632, 0.92982456, 0.71052632,
        0.92982456, 0.71052632, 0.92982456]),
 'split4_test_score': array([0.68141593, 0.92920354, 0.71681416, 0.92035398, 0.71681416,
        0.92035398, 0.71681416, 0.92035398]),
 'mean_test_score': array([0.71698494, 0.90689334, 0.72055581, 0.91389536, 0.72055581,
        0.91740413, 0.72055581, 0.9209129 ]),
 'std_test_score': array([0.02123548, 0.02904976, 0.01796744, 0.02026207, 0.01796744,
        0.01186084, 0.01796744, 0.01840228]),
 'rank_test_score': array([8, 4, 5, 3, 5, 2, 5, 1])}

In [39]:
df =pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.043565,0.001187,0.021936,0.001574,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.710526,0.719298,0.745614,0.728070,0.681416,0.716985,0.021235,8
1,1.459873,0.657245,0.006429,0.000925,1,linear,"{'C': 1, 'kernel': 'linear'}",0.859649,0.885965,0.929825,0.929825,0.929204,0.906893,0.029050,4
2,0.048146,0.006994,0.021045,0.000808,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.701754,0.719298,0.754386,0.710526,0.716814,0.720556,0.017967,5
3,8.504564,2.936727,0.004841,0.000521,10,linear,"{'C': 10, 'kernel': 'linear'}",0.885965,0.894737,0.938596,0.929825,0.920354,0.913895,0.020262,3
4,0.049146,0.004760,0.021227,0.000961,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.701754,0.719298,0.754386,0.710526,0.716814,0.720556,0.017967,5
5,5.509396,1.507995,0.004965,0.000340,20,linear,"{'C': 20, 'kernel': 'linear'}",0.903509,0.903509,0.929825,0.929825,0.920354,0.917404,0.011861,2
6,0.050487,0.002494,0.024266,0.002004,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.701754,0.719298,0.754386,0.710526,0.716814,0.720556,0.017967,5
7,6.194492,1.648537,0.005522,0.000583,30,linear,"{'C': 30, 'kernel': 'linear'}",0.885965,0.929825,0.938596,0.929825,0.920354,0.920913,0.018402,1

In [40]:
clf.best_params_

{'C': 30, 'kernel': 'linear'}